version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - vol12:/var/lib/mysql
    restart: always
    ports:
      - '7000:3306'
    networks:
       - backend
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    networks:
      - frontend
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
volumes:
  vol12:
networks:
  frontend: {}  # Define frontend network
  backend: {}   # Define backend network
